export const cuaHang =  [
    {
        "BranchID": "1b607368-de86-4a2a-b1fa-a4d2a7007030",
        "BranchCode": "10HB",
        "BranchName": "HN - 10 HÀNG BÚN - KHO 1 ",
        "Tel": "0374032846",
        "Email": "phuongthuy11102000@gmail.com",
        "Address": "HN",
        "Country": "Việt Nam",
        "ProvinceOrCity": "",
        "District": "",
        "WardOrCommune": "",
        "Street": "",
        "TaxCode": "",
        "CurrencyID": "VND",
        "IsVirtualBranch": false,
        "Inactive": false,
        "LastStatus": false,
        "CountryCode": "VN",
        "ProvinceOrCityCode": "",
        "DistrictCode": "",
        "WardOrCommuneCode": "",
        "IsInventorySeperate": false,
        "EditMode": 0,
        "CreatedDate": "2025-01-06T11:28:56.467+07:00",
        "CreatedBy": "",
        "ModifiedDate": "2025-02-21T08:35:00.583+07:00",
        "ModifiedBy": "phuongthuy11102000",
        "IsAutoGenPrimaryKey": true,
        "BakEditMode": 0
    },
    {
        "BranchID": "7c366055-6d2f-4992-92d3-54c77886d1b0",
        "BranchCode": "189QUANGTRUNG",
        "BranchName": "HN - 189 QUANG TRUNG - KHO 1 ",
        "Tel": "",
        "Email": "",
        "Address": "HN",
        "Country": "Việt Nam",
        "ProvinceOrCity": "",
        "District": "",
        "WardOrCommune": "",
        "Street": "",
        "TaxCode": "",
        "CurrencyID": "VND",
        "IsVirtualBranch": false,
        "Inactive": false,
        "LastStatus": false,
        "CountryCode": "VN",
        "ProvinceOrCityCode": "",
        "DistrictCode": "",
        "WardOrCommuneCode": "",
        "IsInventorySeperate": false,
        "EditMode": 0,
        "CreatedDate": "2025-02-21T08:35:20.887+07:00",
        "CreatedBy": "phuongthuy11102000",
        "ModifiedDate": "2025-02-21T08:35:20.887+07:00",
        "ModifiedBy": "phuongthuy11102000",
        "IsAutoGenPrimaryKey": true,
        "BakEditMode": 0
    },
    {
        "BranchID": "3f83b38e-c3c8-4030-8dae-106ca1e00e77",
        "BranchCode": "253TRANQUANGKHAI",
        "BranchName": "HCM - 253 TRẦN QUANG KHẢI - KHO 1 ",
        "Tel": "",
        "Email": "",
        "Address": "HCM",
        "Country": "Việt Nam",
        "ProvinceOrCity": "",
        "District": "",
        "WardOrCommune": "",
        "Street": "",
        "TaxCode": "",
        "CurrencyID": "VND",
        "IsVirtualBranch": false,
        "Inactive": false,
        "LastStatus": false,
        "CountryCode": "VN",
        "ProvinceOrCityCode": "",
        "DistrictCode": "",
        "WardOrCommuneCode": "",
        "IsInventorySeperate": false,
        "EditMode": 0,
        "CreatedDate": "2025-02-21T08:35:43.24+07:00",
        "CreatedBy": "phuongthuy11102000",
        "ModifiedDate": "2025-02-21T08:35:43.24+07:00",
        "ModifiedBy": "phuongthuy11102000",
        "IsAutoGenPrimaryKey": true,
        "BakEditMode": 0
    },
    {
        "BranchID": "4173f24c-800f-40dc-a2b8-642e52239902",
        "BranchCode": "320THAIHA",
        "BranchName": "HN- 320 THÁI HÀ - KHO 1 ",
        "Tel": "",
        "Email": "",
        "Address": "HN ",
        "Country": "Việt Nam",
        "ProvinceOrCity": "",
        "District": "",
        "WardOrCommune": "",
        "Street": "",
        "TaxCode": "",
        "CurrencyID": "VND",
        "IsVirtualBranch": false,
        "Inactive": false,
        "LastStatus": false,
        "CountryCode": "VN",
        "ProvinceOrCityCode": "",
        "DistrictCode": "",
        "WardOrCommuneCode": "",
        "IsInventorySeperate": false,
        "EditMode": 0,
        "CreatedDate": "2025-02-21T08:35:59.653+07:00",
        "CreatedBy": "phuongthuy11102000",
        "ModifiedDate": "2025-02-21T08:35:59.653+07:00",
        "ModifiedBy": "phuongthuy11102000",
        "IsAutoGenPrimaryKey": true,
        "BakEditMode": 0
    },
    {
        "BranchID": "06b9265d-b3c3-470a-ad58-34f019424c90",
        "BranchCode": "406CAUGIAY",
        "BranchName": "HN- 406 CẦU GIẤY - KHO 1 ",
        "Tel": "",
        "Email": "",
        "Address": "HN",
        "Country": "Việt Nam",
        "ProvinceOrCity": "",
        "District": "",
        "WardOrCommune": "",
        "Street": "",
        "TaxCode": "",
        "CurrencyID": "VND",
        "IsVirtualBranch": false,
        "Inactive": false,
        "LastStatus": false,
        "CountryCode": "VN",
        "ProvinceOrCityCode": "",
        "DistrictCode": "",
        "WardOrCommuneCode": "",
        "IsInventorySeperate": false,
        "EditMode": 0,
        "CreatedDate": "2025-02-21T08:36:26.197+07:00",
        "CreatedBy": "phuongthuy11102000",
        "ModifiedDate": "2025-02-21T08:36:26.197+07:00",
        "ModifiedBy": "phuongthuy11102000",
        "IsAutoGenPrimaryKey": true,
        "BakEditMode": 0
    },
    {
        "BranchID": "85151a35-e944-44d6-aeaa-466b4f3e3542",
        "BranchCode": "KHO",
        "BranchName": "HN - TĐ KHO - NGHI TÀM ",
        "Tel": "",
        "Email": "",
        "Address": "HN",
        "Country": "Việt Nam",
        "ProvinceOrCity": "",
        "District": "",
        "WardOrCommune": "",
        "Street": "",
        "TaxCode": "",
        "CurrencyID": "VND",
        "IsVirtualBranch": false,
        "Inactive": false,
        "LastStatus": false,
        "CountryCode": "VN",
        "ProvinceOrCityCode": "",
        "DistrictCode": "",
        "WardOrCommuneCode": "",
        "IsInventorySeperate": false,
        "EditMode": 0,
        "CreatedDate": "2025-02-21T08:36:52.267+07:00",
        "CreatedBy": "phuongthuy11102000",
        "ModifiedDate": "2025-02-21T08:36:52.267+07:00",
        "ModifiedBy": "phuongthuy11102000",
        "IsAutoGenPrimaryKey": true,
        "BakEditMode": 0
    },
    {
        "BranchID": "355ac2c1-e5e5-4dda-875c-c15cfd1b540d",
        "BranchCode": "KHOTONG",
        "BranchName": "Kho tổng",
        "Tel": "0374032846",
        "Email": "",
        "Address": "HN",
        "Country": "Việt Nam",
        "ProvinceOrCity": "",
        "District": "",
        "WardOrCommune": "",
        "Street": "",
        "TaxCode": "",
        "CurrencyID": "",
        "IsVirtualBranch": true,
        "Inactive": false,
        "LastStatus": false,
        "CountryCode": "VN",
        "ProvinceOrCityCode": "",
        "DistrictCode": "",
        "WardOrCommuneCode": "",
        "IsInventorySeperate": false,
        "EditMode": 0,
        "CreatedDate": "2025-02-21T08:33:09.463+07:00",
        "CreatedBy": "phuongthuy11102000",
        "ModifiedDate": "2025-02-21T08:33:26.23+07:00",
        "ModifiedBy": "phuongthuy11102000",
        "IsAutoGenPrimaryKey": true,
        "BakEditMode": 0
    },
    {
        "BranchID": "7513f45d-5338-4f73-90ab-9808c34d8222",
        "BranchCode": "TD10HB",
        "BranchName": "HN - 10 HÀNG BÚN - KHO 2 ",
        "Tel": "",
        "Email": "",
        "Address": "HN",
        "Country": "Việt Nam",
        "ProvinceOrCity": "",
        "District": "",
        "WardOrCommune": "",
        "Street": "",
        "TaxCode": "",
        "CurrencyID": "VND",
        "IsVirtualBranch": false,
        "Inactive": false,
        "LastStatus": false,
        "CountryCode": "VN",
        "ProvinceOrCityCode": "",
        "DistrictCode": "",
        "WardOrCommuneCode": "",
        "IsInventorySeperate": false,
        "EditMode": 0,
        "CreatedDate": "2025-02-21T08:37:14.937+07:00",
        "CreatedBy": "phuongthuy11102000",
        "ModifiedDate": "2025-02-21T08:37:14.937+07:00",
        "ModifiedBy": "phuongthuy11102000",
        "IsAutoGenPrimaryKey": true,
        "BakEditMode": 0
    },
    {
        "BranchID": "330e77a1-81eb-41f0-b17d-1ca43d22ea78",
        "BranchCode": "TD189QUANGTRUNG",
        "BranchName": "HN- 189 QUANG TRUNG - KHO 2 ",
        "Tel": "",
        "Email": "",
        "Address": "HN ",
        "Country": "Việt Nam",
        "ProvinceOrCity": "",
        "District": "",
        "WardOrCommune": "",
        "Street": "",
        "TaxCode": "",
        "CurrencyID": "VND",
        "IsVirtualBranch": false,
        "Inactive": false,
        "LastStatus": false,
        "CountryCode": "VN",
        "ProvinceOrCityCode": "",
        "DistrictCode": "",
        "WardOrCommuneCode": "",
        "IsInventorySeperate": false,
        "EditMode": 0,
        "CreatedDate": "2025-02-21T08:37:35.57+07:00",
        "CreatedBy": "phuongthuy11102000",
        "ModifiedDate": "2025-02-21T08:37:35.57+07:00",
        "ModifiedBy": "phuongthuy11102000",
        "IsAutoGenPrimaryKey": true,
        "BakEditMode": 0
    },
    {
        "BranchID": "ce310330-2a4d-4a85-a6ea-15413944edc9",
        "BranchCode": "TD253TQK",
        "BranchName": "HCM - 253 TRẦN QUANG KHẢI - KHO 2",
        "Tel": "",
        "Email": "",
        "Address": "HCM",
        "Country": "Việt Nam",
        "ProvinceOrCity": "",
        "District": "",
        "WardOrCommune": "",
        "Street": "",
        "TaxCode": "",
        "CurrencyID": "VND",
        "IsVirtualBranch": false,
        "Inactive": false,
        "LastStatus": false,
        "CountryCode": "VN",
        "ProvinceOrCityCode": "",
        "DistrictCode": "",
        "WardOrCommuneCode": "",
        "IsInventorySeperate": false,
        "EditMode": 0,
        "CreatedDate": "2025-02-21T08:38:07.753+07:00",
        "CreatedBy": "phuongthuy11102000",
        "ModifiedDate": "2025-02-21T08:38:07.753+07:00",
        "ModifiedBy": "phuongthuy11102000",
        "IsAutoGenPrimaryKey": true,
        "BakEditMode": 0
    },
    {
        "BranchID": "1ca0db0d-a939-4ede-a484-4422a901b596",
        "BranchCode": "TD320THAIHA",
        "BranchName": "HN - 320 THÁI HÀ - KHO 2",
        "Tel": "",
        "Email": "",
        "Address": "HN",
        "Country": "Việt Nam",
        "ProvinceOrCity": "",
        "District": "",
        "WardOrCommune": "",
        "Street": "",
        "TaxCode": "",
        "CurrencyID": "VND",
        "IsVirtualBranch": false,
        "Inactive": false,
        "LastStatus": false,
        "CountryCode": "VN",
        "ProvinceOrCityCode": "",
        "DistrictCode": "",
        "WardOrCommuneCode": "",
        "IsInventorySeperate": false,
        "EditMode": 0,
        "CreatedDate": "2025-02-21T08:38:27.91+07:00",
        "CreatedBy": "phuongthuy11102000",
        "ModifiedDate": "2025-02-21T08:38:27.91+07:00",
        "ModifiedBy": "phuongthuy11102000",
        "IsAutoGenPrimaryKey": true,
        "BakEditMode": 0
    },
    {
        "BranchID": "7ff2b736-cd8f-408b-9a2c-1abaa132573f",
        "BranchCode": "TD406CAUGIAY",
        "BranchName": "HN - 406 CẦU GIẤY - KHO 2",
        "Tel": "",
        "Email": "",
        "Address": "HN",
        "Country": "Việt Nam",
        "ProvinceOrCity": "",
        "District": "",
        "WardOrCommune": "",
        "Street": "",
        "TaxCode": "",
        "CurrencyID": "VND",
        "IsVirtualBranch": false,
        "Inactive": false,
        "LastStatus": false,
        "CountryCode": "VN",
        "ProvinceOrCityCode": "",
        "DistrictCode": "",
        "WardOrCommuneCode": "",
        "IsInventorySeperate": false,
        "EditMode": 0,
        "CreatedDate": "2025-02-21T08:38:53.96+07:00",
        "CreatedBy": "phuongthuy11102000",
        "ModifiedDate": "2025-02-21T08:38:53.96+07:00",
        "ModifiedBy": "phuongthuy11102000",
        "IsAutoGenPrimaryKey": true,
        "BakEditMode": 0
    }
]